model:
  method: tss
  n_hidden: 64
  n_layer: 2
  act: F.relu
  dropout: 0.5
  norm_info: ~
  input_layer: false
  output_layer: false
  lam: 0.25
  T: 400
  scheduler: linear
  pagerank-prob: 0.85
  ppr-topk: -1

training:
  lr: 1e-2
  weight_decay: 5e-4
  n_epochs: 500
  patience: ~
  criterion: metric
  pretrain_epoch: 400

dataset:
  sparse: true

analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false