analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  act: F.relu
  heads: 5
  negative_slope: 0.8383202163955352
  input_layer: false
  norm_info: null
  output_layer: false
training:
  criterion: metric
  lr: 0.001
  weight_decay: 0.005
  n_epochs: 200
  patience: null
