analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  alpha: 0.2
  dropout: 0.7522177198031871
  heads: 4
  input_layer: false
  layer: 1
  module: gat_gcn2_v2
  n_hidden: 64
  negative_slope: 0.614431890616775
  norm_info: null
  output_layer: false
  theta: 0.1
training:
  criterion: metric
  lr: 0.005
  n_epochs: 200
  patience: null
  weight_decay: 0.001
