analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  alpha: 0.7
  dropout: 0.5120171717710084
  heads: 4
  input_layer: false
  layer: 1
  module: gat_gcn_v2
  n_hidden: 128
  negative_slope: 0.10955110830050795
  norm_info: null
  output_layer: false
  theta: 0.1
training:
  criterion: metric
  lr: 0.01
  n_epochs: 200
  patience: null
  weight_decay: 0.005
