analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  act: F.relu
  dropout: 0.4628544157737705
  input_layer: false
  heads: 1
  negative_slope: 0.2
  norm_info: null
  output_layer: false
training:
  criterion: metric
  lr: 0.05
  n_epochs: 200
  patience: null
  weight_decay: 0.005