model:
  method: gcn
  n_hidden: 64
  n_layer: 2
  act: F.relu
  dropout: 0.5
  norm_info: ~
  input_layer: false
  output_layer: false
  k: 1
  alpha: 0.5
  beta: 0.5

training:
  lr: 5e-3
  weight_decay: 5e-3
  n_epochs: 200
  patience: 50
  criterion: metric

dataset:
  sparse: true

analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false