model:
  method: cp
  n_hidden: 64
  n_layer: 2
  act: F.relu
  dropout: 0.5
  norm_info: ~
  input_layer: false
  output_layer: false

  n_cluster: 8
  lam: 0.2
  emb_p: 1.0
  emb_q: 1.0
  emb_num_negative_samples: 1
  emb_batch_size: 128
  emb_num_workers: 1
  emb_dim: 128
  emb_walks_per_node: 10
  emb_walk_length: 20
  emb_context_size: 10


training:
  lr: 1e-2
  weight_decay: 5e-4
  n_epochs: 200
  emb_epochs: 100
  patience: ~
  criterion: metric

dataset:
  sparse: true

analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false