model:
  method: pignn
  n_hidden: 64
  n_layer: 2
  act: F.relu
  dropout: 0.4
  norm_info: ~
  input_layer: false
  output_layer: false

training:
  lr: 5e-3
  weight_decay: 5e-3
  n_epochs: 400
  start_epoch: 50
  patience: ~
  criterion: metric

dataset:
  sparse: true

analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false