analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  act: F.relu
  alpha: 77
  alpha1: 0.41849429512562086
  alpha2: 0.2774917945166447
  alpha3: 0.7464219771110537
  beta: 0.1
  delta: 0.9
  dropout: 0.6525090091600686
  gamma: 0.5500486182845634
  input_layer: false
  method: r2lp
  n_hidden: 64
  n_layer: 2
  norm_func_id: 1
  norm_info: null
  norm_layers: 2
  orders: 6
  orders_func_id: 2
  output_layer: false
  pre_select: 0.5
training:
  criterion: metric
  lr: 0.02
  n_epochs: 200
  n_epochs_lp: 10
  patience: null
  pre_select: 0.5
  pre_unknown: 0.5
  weight_decay: 0.0005
