analysis:
  flag: false
  project: gnn-with-label-noise
  save_graph: false
dataset:
  sparse: true
model:
  act: F.relu
  alpha: 0.0
  alpha1: 0.30912129146737455
  alpha2: 0.5981498358521556
  alpha3: 0.7798412536873742
  beta: 1000
  delta: 0.0
  dropout: 0.7766253011401179
  gamma: 0.6564235042467665
  input_layer: false
  method: r2lp
  n_hidden: 32
  n_layer: 2
  norm_func_id: 1
  norm_info: null
  norm_layers: 2
  orders: 1
  orders_func_id: 2
  output_layer: false
  pre_select: 0.2
training:
  criterion: metric
  lr: 0.3
  n_epochs: 200
  n_epochs_lp: 10
  patience: null
  pre_select: 0.5
  pre_unknown: 0.5
  weight_decay: 5e-05
